/*
==============================================================================

human heavy weapons

==============================================================================
*/

$modelname "Hvyweapons\compile\hassault.mdl"
$cd ".\Hvyweapons"
$cdtexture ".\Hvyweapons\maps_8bit"

$scale 1.0


// whole body
$body studio "reference(final)"

$body studio "gunreference"

$include ".\Hvyweapons\heavy_shared.qc"

